# Generated by Django 5.2.8 on 2025-11-24 10:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='设备ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='设备名称')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='安装位置')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC地址')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP地址')),
                ('status', models.CharField(choices=[('waiting', '等待部署'), ('deploying', '部署中'), ('online', '在线'), ('offline', '离线'), ('updating', '更新中'), ('error', '异常')], default='waiting', max_length=20, verbose_name='状态')),
                ('current_version', models.CharField(blank=True, max_length=50, verbose_name='当前版本')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
                ('cpu_usage', models.FloatField(default=0, verbose_name='CPU使用率')),
                ('memory_usage', models.FloatField(default=0, verbose_name='内存使用率')),
                ('disk_usage', models.FloatField(default=0, verbose_name='磁盘使用率')),
                ('config', models.JSONField(default=dict, verbose_name='设备配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备列表',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_id'], name='management__device__3750fd_idx'), models.Index(fields=['status'], name='management__status_58b17b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeploymentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_version', models.CharField(max_length=50, verbose_name='目标版本')),
                ('config', models.JSONField(default=dict, verbose_name='部署配置')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('downloading', '下载中'), ('configuring', '配置中'), ('starting', '启动中'), ('checking', '检查中'), ('completed', '完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(%)')),
                ('message', models.TextField(blank=True, verbose_name='状态消息')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '部署任务',
                'verbose_name_plural': '部署任务列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_version', models.CharField(max_length=50, verbose_name='原版本')),
                ('target_version', models.CharField(max_length=50, verbose_name='目标版本')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('downloading', '下载中'), ('installing', '安装中'), ('success', '成功'), ('failed', '失败'), ('rolled_back', '已回滚')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(%)')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '更新任务',
                'verbose_name_plural': '更新任务列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', '调试'), ('INFO', '信息'), ('WARNING', '警告'), ('ERROR', '错误'), ('CRITICAL', '严重')], max_length=10, verbose_name='级别')),
                ('message', models.TextField(verbose_name='日志内容')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间戳')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备日志',
                'verbose_name_plural': '设备日志列表',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='management__device__8a1913_idx'), models.Index(fields=['level', '-timestamp'], name='management__level_ad8c7c_idx')],
            },
        ),
    ]
