# Generated by Django 5.2.8 on 2025-11-24 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymenttask',
            name='container_config',
            field=models.JSONField(default=dict, verbose_name='容器配置'),
        ),
        migrations.AddField(
            model_name='deploymenttask',
            name='container_name',
            field=models.CharField(default='middleware', max_length=255, verbose_name='容器名称'),
        ),
        migrations.AddField(
            model_name='deploymenttask',
            name='registry_url',
            field=models.CharField(default='localhost:5000', max_length=500, verbose_name='Registry地址'),
        ),
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='镜像名称')),
                ('tag', models.CharField(max_length=100, verbose_name='版本标签')),
                ('full_name', models.CharField(max_length=500, unique=True, verbose_name='完整名称')),
                ('size', models.BigIntegerField(verbose_name='镜像大小(字节)')),
                ('file_path', models.CharField(max_length=1000, verbose_name='本地存储路径')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_by', models.CharField(default='admin', max_length=100, verbose_name='上传者')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': 'Docker镜像',
                'verbose_name_plural': 'Docker镜像列表',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['name', 'tag'], name='management__name_703340_idx'), models.Index(fields=['-uploaded_at'], name='management__uploade_0b2774_idx')],
            },
        ),
        migrations.AddField(
            model_name='deploymenttask',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.dockerimage', verbose_name='关联镜像'),
        ),
    ]
