# Generated by Django 5.0.6 on 2025-11-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_deploymenttask_container_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymenttask',
            name='task_type',
            field=models.CharField(choices=[('deploy', '部署'), ('restart', '重启')], default='deploy', max_length=20, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='deploymenttask',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('downloading', '下载中'), ('configuring', '配置中'), ('starting', '启动中'), ('running', '运行中'), ('checking', '检查中'), ('completed', '完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
