# Generated by Django 5.0.6 on 2025-11-25 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_deploymenttask_task_type_alter_deploymenttask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.CharField(blank=True, help_text='如：XX医院-流水线A', max_length=100, verbose_name='设备分组'),
        ),
        migrations.AddField(
            model_name='device',
            name='tags',
            field=models.JSONField(default=list, help_text='标签数组，用于分类和筛选', verbose_name='标签'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('version', models.CharField(max_length=50, verbose_name='当前版本')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '活跃'), ('archived', '归档')], default='active', max_length=20, verbose_name='状态')),
                ('git_repo', models.CharField(blank=True, max_length=500, verbose_name='Git仓库地址')),
                ('git_branch', models.CharField(default='main', max_length=100, verbose_name='Git分支')),
                ('work_dir', models.CharField(default='/app', max_length=500, verbose_name='工作目录')),
                ('start_command', models.TextField(default='python main.py', verbose_name='启动命令')),
                ('container_name', models.CharField(default='app', max_length=255, verbose_name='容器名称')),
                ('container_config', models.JSONField(default=dict, verbose_name='容器配置')),
                ('created_by', models.CharField(default='admin', max_length=100, verbose_name='创建者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('docker_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.dockerimage', verbose_name='Docker镜像')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='auto_deploy_project',
            field=models.ForeignKey(blank=True, help_text='设备上线时自动部署此项目', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.project', verbose_name='自动部署项目'),
        ),
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('is_secret', models.BooleanField(default=False, verbose_name='是否敏感信息')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='management.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目配置',
                'verbose_name_plural': '项目配置列表',
                'ordering': ['project', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('pulling_image', '拉取镜像'), ('pulling_code', '拉取代码'), ('configuring', '配置中'), ('starting', '启动中'), ('running', '运行中'), ('completed', '完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(%)')),
                ('message', models.TextField(blank=True, verbose_name='状态消息')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('deployed_version', models.CharField(max_length=50, verbose_name='部署版本')),
                ('git_commit', models.CharField(blank=True, max_length=40, verbose_name='Git提交hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.device', verbose_name='设备')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目部署',
                'verbose_name_plural': '项目部署列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='management__status_3f7f12_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created_at'], name='management__created_44abd8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectconfig',
            unique_together={('project', 'key')},
        ),
        migrations.AddIndex(
            model_name='projectdeployment',
            index=models.Index(fields=['status'], name='management__status_24f2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdeployment',
            index=models.Index(fields=['device', '-created_at'], name='management__device__87327f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdeployment',
            index=models.Index(fields=['project', '-created_at'], name='management__project_869ca9_idx'),
        ),
    ]
