# Generated by Django 5.0.6 on 2025-11-25 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_device_group_device_tags_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectconfig',
            options={'verbose_name': '项目配置', 'verbose_name_plural': '项目配置列表'},
        ),
        migrations.RemoveIndex(
            model_name='dockerimage',
            name='management__name_703340_idx',
        ),
        migrations.RemoveIndex(
            model_name='dockerimage',
            name='management__uploade_0b2774_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='management__status_3f7f12_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='management__created_44abd8_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectdeployment',
            name='management__status_24f2b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectdeployment',
            name='management__device__87327f_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectdeployment',
            name='management__project_869ca9_idx',
        ),
        migrations.RemoveField(
            model_name='deploymenttask',
            name='container_config',
        ),
        migrations.RemoveField(
            model_name='deploymenttask',
            name='container_name',
        ),
        migrations.RemoveField(
            model_name='deploymenttask',
            name='image',
        ),
        migrations.RemoveField(
            model_name='deploymenttask',
            name='registry_url',
        ),
        migrations.RemoveField(
            model_name='deploymenttask',
            name='task_type',
        ),
        migrations.AlterField(
            model_name='deploymenttask',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('downloading', '下载中'), ('configuring', '配置中'), ('starting', '启动中'), ('checking', '检查中'), ('completed', '完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='device',
            name='auto_deploy_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.project', verbose_name='自动部署项目'),
        ),
        migrations.AlterField(
            model_name='device',
            name='group',
            field=models.CharField(blank=True, max_length=100, verbose_name='设备分组'),
        ),
        migrations.AlterField(
            model_name='device',
            name='tags',
            field=models.JSONField(default=list, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='projectconfig',
            name='is_secret',
            field=models.BooleanField(default=False, verbose_name='是否敏感'),
        ),
        migrations.AlterField(
            model_name='projectdeployment',
            name='git_commit',
            field=models.CharField(blank=True, max_length=40, verbose_name='Git提交'),
        ),
    ]
