# Generated by Django 5.0.6 on 2025-11-25 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_projectconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='包名称')),
                ('version', models.CharField(max_length=50, verbose_name='版本')),
                ('file_path', models.CharField(max_length=1000, verbose_name='文件路径')),
                ('size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='校验和')),
                ('description', models.TextField(blank=True, verbose_name='更新说明')),
                ('created_by', models.CharField(default='admin', max_length=100, verbose_name='上传者')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '代码包',
                'verbose_name_plural': '代码包列表',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='code_mount_path',
            field=models.CharField(default='/opt/project-code', max_length=500, verbose_name='代码挂载路径(宿主机)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='docker_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.dockerimage', verbose_name='Docker镜像(环境)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='git_repo',
            field=models.CharField(blank=True, max_length=500, verbose_name='Git仓库地址(备用)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_command',
            field=models.TextField(default='/start.sh', verbose_name='启动命令'),
        ),
        migrations.AlterField(
            model_name='project',
            name='work_dir',
            field=models.CharField(default='/work', max_length=500, verbose_name='容器内工作目录'),
        ),
        migrations.AddField(
            model_name='project',
            name='code_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.codepackage', verbose_name='代码包'),
        ),
    ]
