# Generated by Django 5.0.6 on 2025-12-09 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_codepackage_project_code_mount_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='container_name',
            field=models.CharField(blank=True, default='middleware', max_length=100, verbose_name='容器名称'),
        ),
        migrations.AddField(
            model_name='device',
            name='container_status',
            field=models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('not_found', '未找到'), ('error', '异常')], default='not_found', max_length=20, verbose_name='容器状态'),
        ),
        migrations.AddField(
            model_name='device',
            name='container_uptime',
            field=models.CharField(blank=True, max_length=100, verbose_name='容器运行时长'),
        ),
        migrations.AddField(
            model_name='device',
            name='health_check_url',
            field=models.CharField(blank=True, default='http://localhost:8000/api/', max_length=200, verbose_name='健康检查URL'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_health_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后健康检查时间'),
        ),
        migrations.AddField(
            model_name='device',
            name='service_response_time',
            field=models.IntegerField(default=0, verbose_name='服务响应时间(ms)'),
        ),
        migrations.AddField(
            model_name='device',
            name='service_status',
            field=models.CharField(choices=[('healthy', '健康'), ('unhealthy', '不健康'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='服务状态'),
        ),
        migrations.AddField(
            model_name='project',
            name='local_image_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='本地镜像名称(设备预装)'),
        ),
        migrations.AddField(
            model_name='projectdeployment',
            name='task_type',
            field=models.CharField(choices=[('deploy', '部署'), ('restart', '重启')], default='deploy', max_length=20, verbose_name='任务类型'),
        ),
        migrations.CreateModel(
            name='DeviceConfigHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_data', models.JSONField(verbose_name='配置数据')),
                ('applied_by', models.CharField(max_length=100, verbose_name='操作人')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='应用时间')),
                ('status', models.CharField(choices=[('pending', '待应用'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('is_active', models.BooleanField(default=False, verbose_name='当前生效')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_history', to='management.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备配置历史',
                'verbose_name_plural': '设备配置历史列表',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['device', '-applied_at'], name='management__device__bb9d7c_idx'), models.Index(fields=['device', 'is_active'], name='management__device__10e25e_idx')],
            },
        ),
    ]
