# Generated by Django 5.2.8 on 2026-02-05 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_device_container_name_device_container_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrpServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_addr', models.CharField(help_text='FRP服务器地址', max_length=255)),
                ('server_port', models.IntegerField(help_text='FRP服务器端口')),
                ('token', models.CharField(help_text='认证Token', max_length=255)),
                ('port_pool_start', models.IntegerField(help_text='端口池起始')),
                ('port_pool_end', models.IntegerField(help_text='端口池结束')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'FRP服务器配置',
                'verbose_name_plural': 'FRP服务器配置',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='frp_error_message',
            field=models.TextField(blank=True, help_text='FRP错误信息'),
        ),
        migrations.AddField(
            model_name='device',
            name='frp_last_check',
            field=models.DateTimeField(blank=True, help_text='FRP状态最后检查时间', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='frp_ssh_port',
            field=models.IntegerField(blank=True, help_text='分配的SSH端口', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='frp_status',
            field=models.CharField(choices=[('disconnected', '未连接'), ('connecting', '连接中'), ('connected', '已连接'), ('error', '错误')], default='disconnected', max_length=20, verbose_name='FRP状态'),
        ),
        migrations.AddField(
            model_name='device',
            name='frp_web_port',
            field=models.IntegerField(blank=True, help_text='分配的Web端口', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='docker_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.dockerimage', verbose_name='Docker镜像(平台托管)'),
        ),
        migrations.AlterField(
            model_name='projectdeployment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.project', verbose_name='项目'),
        ),
    ]
